# Generated by Django 5.0.2 on 2024-03-27 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogger", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="publish_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
