# Generated by Django 5.0.2 on 2024-03-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogger", "0002_alter_blog_publish_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="update_date",
            field=models.DateTimeField(),
        ),
    ]
