# Generated by Django 5.0.2 on 2024-03-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogger", "0004_alter_blog_publish_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="publish_date",
            field=models.DateTimeField(),
        ),
    ]
