# Generated by Django 5.0.2 on 2024-03-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogger", "0005_alter_blog_publish_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="publish_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="update_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
