# Generated by Django 5.0.2 on 2024-04-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogger", "0007_blog_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="update_date",
            field=models.DateTimeField(null=True),
        ),
    ]
