# Generated by Django 5.0.2 on 2024-04-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogger", "0008_alter_blog_update_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
